defaults/main.yml
templates/virt-network.j2

The network template expected NAT and DHCP, however sometimes it might
be useful to have an isolated network without DHCP or NAT.
This can be achieved by specifying the type to "isolated". You can also
have a NAT network without DHCP by leaving out DHCP ranges. Backwards
compatible behaviour is maintained by making NAT the default type,
however NAT only works if you specify a network range and IP address.
Thus, if both `type` and ip_address` are not specified then it will be
isolated.
Example NAT network with DHCP:
- name: "example-nat-dhcp"
ip_address: "192.168.112.1"
subnet: "255.255.255.0"
dhcp_start: "192.168.112.2"
dhcp_end: "192.168.112.99"
Example NAT network without DHCP:
- name: "example-nat-no-dhcp"
type: "nat"
ip_address: "192.168.112.1"
subnet: "255.255.255.0"
Example isolated …

support isolated networks

---

tasks/disk-create.yml

If you're using RHEL guest, installing packages (including cloud-init)
requires the guest to be registered to the portal.
This is too tricky. If you're using RHEL do it manually in your base
image.

Register RHEL guests to ports for package install

---

tasks/virt-create.yml

There was an issue previously where cloud-init did not discover the ISO
on boot, causing it to fail.
To fix this, the CDROM device was added directly after root.
However in subsequent tests with lots of disks, it appears extra
controllers are added and the CDROM goes onto a different LSI one. This
appears to be behind the CDROM not being detected by cloud-init.
Thus, to fix this, we're adding two controllers both of type
virtio-scsi. This way both the disks and CD-ROM are on the same
controller type and it improves detection at boot.
This also means that adding the boot disk and CDROM don't need to be
treated specially and boot can be done in the loop.
This also fixes an issue where boot is not the first disk listed in the
vm's disks, by always setting it to be the first boot device.
If …

add disks in a clearer way

---

tasks/disk-create.yml

If spinning up a RHEL guest without specifying portal credentials, this
step will fail. As the cloud image already has cloud-init this is not
strictly necessary, so we can not skip attempting this if no creds were
provided.

skip deps install into rhel vm if no portal creds

---

tasks/virt-create.yml

SCSI disks can set new variable of 'ssd = true' in the YAML inventory in
order to set them as non-rotational disks (SSDs).
In order to enable SSD support we must know the alias of the disk, which
unfortunately we are not able to define ourselves with virt-install.
The alias is generated from the controller number and the disk location
on that controller. For example, 'scsi0-0-0-1' is the second device on
the first controller. This format is only true for the virtio-scsi
controller, the LSI controller would have a slightly different format
'scsi0-0-1' for the same disk.
In order to calculate the alias, we need to know which controller the
disk is on and its location. And in order to do that, we need to count
the number of SCSI disks as well as the controllers.
The SCSI controllers have a …

support ssd for scsi disks and dynamic controllers

---

README.md
tasks/virt-create.yml

It may be useful to specify a MAC address for VMs so that they are
always the same when recreated. For example, when they are used for
external DHCP leases on a bridged network, or for PXE boot, etc.
This adds a new "mac" YAML option for VM network interfaces and works
with every network type, e.g.:
test-0:
virt_infra_networks:
- name: br0
type: bridge
mac: 52:54:00:aa:bb:cc

add support for custom VM MAC addresses

---

tasks/virt-create.yml

The default bus is scsi, so if it is not specified we still need to
increment the scsi counter. This was causing an extra controller to be
added when it wasn't needed.
This patch increments the counter when bus is scsi or not specified, and
fixes the number of disks required before a new controller is required
for the CD-ROM drive.

fix scsi count

---

tasks/disk-create.yml
tasks/disk-remove.yml
tasks/virt-remove.yml

This change adds the ability to keep a disk rather than delete it when a
guest is undefined.
This adds a new 'keep' disk config item. Setting this to true will cause
the disk to be skipped when the machine is undefined.
If this is the boot disk, then if you re-create the same guest after
it's deletion, the disk will not have sysprep run on it, or cloud-init,
etc installed.
Thus, you can set 'keep = true' on the boot disk and after the first
time it's created it will remain the same over subsequent guest deletes
and recreates.

add support for keeping disks

---

tasks/disk-create.yml

Recent changes failed when virt_infra_variant is not defined. As it is
not a required variable, this changed fixes the check.

fix errors when vars are undefined

---

tasks/virt-create.yml

Originally we told virt-install to boot from hard drive (--boot hd)
however as a part of commit bc99a15, "add disks in a clearer way, we
now specify a boot order when defining the disks.
On Debian, having both caused a conflict and the guests could not be
defined. This change removes the --boot option as we can now just depend
on the disk boot order.

fix boot order conflict on Debian

---

defaults/main.yml
tasks/disk-create.yml
tasks/validations.yml
vars/centos.yml
vars/debian.yml
vars/fedora.yml
vars/opensuse.yml
vars/ubuntu.yml

Most distros implement mandatory access controls like SELinux and
Apparmor around libvirt. However, NVMe drives are attached via extra
qemu commands and this causes launching of guests to fail as access to
the drives is blocked.
This change adds a new variable `virt_infra_security_driver` which lets
you set the mandatory access control driver you want to use. By default
this is set to "none" which disables it, however RPM distros are set to
"selinux" while Deb based distros are set to "apparmor" by default.
On Fedora, setting the right ownership of the drives seems to make this
work with SELinux. However, this is not enough on Debian and Ubuntu where
Apparmor still blocks reading with an error like this:
audit: type=1400 audit(1588465721.729:1232):
apparmor="DENIED" operation="open" …

add support to set qemu security driver

---

defaults/main.yml
handlers/main.yml
tasks/main.yml
tasks/validations.yml
tasks/vbmc-create.yml
tasks/vbmc-list.yml
tasks/vbmc-remove.yml
templates/vbmcd.service.j2
templates/virtualbmc.conf.j2
vars/centos.yml
vars/debian.yml
vars/fedora.yml
vars/opensuse.yml
vars/ubuntu.yml

This enables option for creating and removing vbmc interfaces for
guests, so that they can be controlled with IPMI.
By default vbmc is disabled, set this in kvmhost vars to enable it:
virt_infra_vbmc: true
If enabled, by default this will install the latest virtualbmc from pip and
configure it to run as root. You may specify a specific version of
virtualbmc, e.g. 1.6.0, with the following var:
virt_infra_vbmc_pip_version: 1.6.0
However, Fedora and openSUSE do package virtualbmc, so if you'd rather
use the system package (or install it manually), you can disable pip
install:
virt_infra_vbmc_pip: false
The default service is called "vbmcd" so if it is called something else
on your distro (like "virtualbmc") then specify it with the following on
kvmhost:
virt_infra_vbmc_service: virtualbmc …

add support for virtual bmc

---

tasks/validations.yml

When VMs are connected to a bridge they can be sent to iptables for processing.
This is generally not desired for VM on a bridge, as it will block
traffic coming in to the VM.
This patch makes sure that, if br_netfilter exists, it is loaded and
then disabled on bridges with sysctl.

ensure netfilter disabled on bridges

---

tasks/validations.yml

The kvmhost must be included in the limit so that the guests can be
created. A check exists to make sure this is included, however if limit
is set to "all" it will also include kvmhost, so we should not fail in
this case (it's the same as excluding a limit).

pass kvmhost check when --limit set to "all"

---

tasks/virt-remove.yml

When undefining a VM, if the guest has snapshots it will fail to be
deleted and cleaned up.
This patch passes the options to virsh to remove all saved data and
snapshots for the VM so taht it can be cleaned up.

remove snapshots and saved data when undefine vm

---

tasks/validations.yml

We must run against the KVM host in order to do anything. If no limit
option is set to specify which hosts or hostgroups to run against, we're
fine as kvmhost will be included.
However, if --limit is specified we have to make sure that the KVM host
will be in that list.
Currently we check if either 'kvmhost' is in the limit option or the
limit option is equal to 'all'. However, this does not cater for more
complex limits like 'all,!not-this-vm' and cases where 'kvmhost' and
'all' are anywhere in the option.
This patch makes the check more robust, by converting the option into a
list. This way we can just check that 'all' or 'kvmhost' are in there.

support for complex --limit options

---

README.md
tasks/virt-create.yml
templates/virt-network.j2

This patch allows you to set the MTU for libvirt networks on KVM host as
well as for guest interfaces.
Simply add the `mtu` option to your kvmhost network definitions and/or
your guest network interfaces definitions. When setting on a libvirt
host network and specifying an IP, that interface will get that MTU.
Also note that setting the MTU for an OVS host network is not supproted
by libvirt and will be ignored. However, setting an MTU for a guest
connected to an OVS network is supported.
Note that if you're connecting your guest to a bridge, the bridge on the
KVM host should also have been set to the same or higher MTU.

add MTU support on libvirt and guest networks

---

README.md
tasks/validations.yml

Update the documentation to support the latest distro releases, like
Fedora 32, Ubuntu Focal (20.04) and openSUSE 15.2.
Match on zero or more spaces for the security driver regex. This will
help make it more robust and also put it in the right place.

doco updates, tweak libvirt security driver regex

---

tasks/disk-create.yml

It might be useful to run commands on the boot disk of a guest before it
is launched. For example, to set a local mirror, or set a proxy, etc.
This is run as a part of the disk-create.yaml task, after the disk is
created and before cloud-init and qemu-guest-agent are installed.
Simply create a list of shell commands that you want to be run against a
machine, through the `virt_infra_disk_cmd` variable.
For example, to set the mirror to use on a Fedora box:
virt_infra_disk_cmd:
- dnf config-manager --save --setopt baseurl=http://path-to-mirror fedora
- dnf config-manager --save --setopt baseurl=http://path-to-mirror-updates updates
Just make sure that it is valid shell commands and it will get run on
the disk as root. Note that the VM will have host networking and should
be able to get out …

Add ability to run shell commands in guest disk

---

tasks/validations.yml
tasks/vbmc-create.yml
tasks/vbmc-list.yml
tasks/vbmc-remove.yml

On distros like CentOS, /usr/local/bin is not in the sudoers path. This
means that all vbmc commands fail.
Rather than modify secure_path in /etc/sudoers, let's just get the path
and use that. This makes vbmc work, but also means the vbmc from the
user's path will be used.
Fixes #28

get the path of vbmc for use with commands

---

tasks/disk-create.yml
tasks/validations.yml
tasks/vbmc-create.yml
tasks/vbmc-list.yml
tasks/vbmc-remove.yml
tasks/virt-create.yml
tasks/wait.yml
vars/opensuse.yml

This fixes a few small things:
- always get path for vbmc, required if system package or pip used
- set SELinux attributes on NVMe drives to ensure it works in enforcing
- fix check for SSD where bool check failed on some systems
- add missing args to use bash with shell command

various fixes

---

README.md
defaults/main.yml
tasks/disk-create.yml
vars/rhel.yml

By default we make sure that cloud-init and qemu-guest-agent are
installed into the VM so that it can be configured on boot. If the image
already includes them, then this step can be skipped. Furthermore, you
might want to have different or additional packages installed.
This patch introduces a comma separated variable of
`virt_infra_guest_deps` which defaults to the existing values of
"cloud-init,qemu-guest-agent".
To skip installation of any packages, set this to an empty string in
your inventory, e.g.
virt_infra_guest_deps: ""
If you want to install different packages then make a new list, e.g.:
virt_infra_guest_deps: "cloud-init,qemu-guest-agent,vim,git,rsync"
As with all vars these can be at the host or group level.
This patch also includes vars/rhel.yml which was missing for RHEL …

turn guest deps into variable

---

tasks/disk-create.yml

By default the boot disk is created using the specified distro disk
image as a backing file.
This commits add a new boolean disk option, `clone` which will copy the
source distro disk to be used as the boot disk image instead.
Due to the way that convert and create subcommands from qemu-img work,
the size of the boot disk is now done as a separate step.
Additional disks are also now done as a separate step.
This commit should also pave the way for using RAW disk images instead
of qcow2, as they do not support backing files.

add support for cloned boot disk instead of backed

---

defaults/main.yml
tasks/disk-create.yml
tasks/virt-create.yml
templates/network-config.j2
vars/centos.yml
vars/debian.yml
vars/fedora.yml
vars/opensuse.yml
vars/redhat.yml
vars/ubuntu.yml

This patchset enables support for basic network configuration v2 using
cloud-init. Currently only ethernet devices are supported (not bonds,
bridges or VLANs).
For details, see the cloud-init documentation:
https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html
As not all distros may support this, in order to activate network config
please enable the following variable:
virt_infra_network_config: true
The network config is then populated with new optional network
configuration options for each VM's network interfaces, including:
- device (string, to set the interface device name, e.g. eth0)
- addresses (list)
- gateway4 (string, IPv4 default gateway)
- gateway6 (string, IPv6 default gateway)
- nameservers (dict)
- search (list of DNS domain search)
- addresses …

add support for network config via cloud-init

---

README.md
defaults/main.yml
handlers/main.yml
tasks/defaults-get.yml
tasks/defaults-set.yml
tasks/disk-create.yml
tasks/disk-remove.yml
tasks/hosts-add.yml
tasks/hosts-remove.yml
tasks/main.yml
tasks/net-create.yml
tasks/net-list.yml
tasks/net-remove.yml
tasks/validations-initial.yml
tasks/validations.yml
tasks/vbmc-create.yml
tasks/vbmc-list.yml
tasks/vbmc-remove.yml
tasks/virt-create.yml
tasks/virt-list.yml
tasks/virt-remove.yml
tasks/wait.yml
templates/user-data.j2

Originally this role was only designed to run on a single host, but it
seems useful to be able to use the one inventory across multiple KVM
hosts.
This change introduces the ability to specify multiple KVM hosts in the
kvmhost group. To do so, add hosts to the `kvmhost` group in your
kvmhost inventory.
For example, here we specify three KVM hosts.
---
kvmhost:
hosts:
kvmhost1:
kvmhost2:
kvmhost3:
vars:
ansible_python_interpreter: /usr/bin/python3
virt_infra_host_networks:
absent: []
present:
- name: "default"
ip_address: "192.168.112.1"
subnet: "255.255.255.0"
dhcp_start: "192.168.112.2"
dhcp_end: "192.168.112.254"
To have a VM land on a specific KVM host, you must add the variable
`kvmhost` with a string that matches a KVM host from the `kvmhost`
group.
For example, six CentOS and six …

add support for multiple KVM hosts

---

tasks/virt-create.yml

Remove `on_poweroff=preserve` as it has been forbidden in libvirt v7.7.0.

Fix using libvirt >= v7.7.0

---

README.md

Red Hat machines need to be registered to their portal in order to
install packages. The role already supports this through the
`virt_infra_sm_creds` variable (which follows
https://libguestfs.org/virt-builder.1.html#subscription-manager
standard), however it wasn't documented.

docs: how to register to Red hat portal

---

defaults/main.yml

The default CentOS 8 image from 2021 had an issue where updates to
cloud-init stopped it from working. This updates it to a 2022 image
which does not have the issue.
Fixes #66

update default CentOS Stream 8 image

---

defaults/main.yml
tasks/virt-create.yml

Currently this defaults to spice however some clients may not support it, so make this configurable.
New option can be vnc or spice, defaults to the latter.
virt_infra_graphics: spice

support graphics server option
